// Regression alerts banner. Shows unacknowledged twin_regression_alerts
// generated by nightly scheduled runs or on-demand verify runs.
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, BellOff } from "lucide-react";

interface Alert {
  id: string; run_id: string | null; severity: string; kind: string;
  message: string; readiness_score: number | null; previous_score: number | null;
  details: Record<string, unknown>; created_at: string;
}

export function RegressionAlerts({ onSelectRun }: { onSelectRun?: (runId: string) => void }) {
  const [alerts, setAlerts] = useState<Alert[]>([]);

  const load = async () => {
    const { data } = await supabase.from("twin_regression_alerts")
      .select("*").is("acknowledged_at", null)
      .order("created_at", { ascending: false }).limit(20);
    setAlerts((data as Alert[] | null) ?? []);
  };

  useEffect(() => {
    load();
    const ch = supabase.channel("twin-alerts")
      .on("postgres_changes", { event: "*", schema: "public", table: "twin_regression_alerts" }, load)
      .subscribe();
    return () => { supabase.removeChannel(ch); };
  }, []);

  const ack = async (id: string) => {
    const { data: u } = await supabase.auth.getUser();
    await supabase.from("twin_regression_alerts")
      .update({ acknowledged_at: new Date().toISOString(), acknowledged_by: u.user?.id ?? null })
      .eq("id", id);
    load();
  };

  if (alerts.length === 0) return null;

  return (
    <Card className="border-status-warning/50 bg-status-warning/40 dark:bg-status-warning/10">
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2 text-status-warning dark:text-status-warning">
          <AlertTriangle className="h-4 w-4" />
          {alerts.length} unacknowledged regression alert{alerts.length === 1 ? "" : "s"}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        {alerts.map((a) => (
          <div key={a.id} className="flex items-start justify-between gap-3 p-2 rounded border bg-background">
            <div className="flex items-start gap-2 min-w-0">
              <Badge variant={a.severity === "critical" ? "destructive" : "secondary"}>{a.severity}</Badge>
              <div className="min-w-0">
                <div className="text-sm font-medium truncate">{a.message}</div>
                <div className="text-xs text-muted-foreground">
                  <span className="font-mono">{a.kind}</span> · {new Date(a.created_at).toLocaleString()}
                  {a.previous_score !== null && a.readiness_score !== null &&
                    ` · ${a.previous_score} → ${a.readiness_score}`}
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              {a.run_id && onSelectRun && (
                <Button variant="outline" size="sm" onClick={() => onSelectRun(a.run_id!)}>View run</Button>
              )}
              <Button variant="ghost" size="sm" onClick={() => ack(a.id)}>
                <BellOff className="h-3.5 w-3.5 mr-1" /> Ack
              </Button>
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
