REVOKE ALL ON FUNCTION public._logistics_notify(_event text, _package_id uuid, _attempt_id uuid, _return_id uuid, _otp_id uuid, _recipient text, _payload jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_delivery_authorised(_action text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_assign(_route_id uuid, _driver_user_id uuid, _vehicle_id uuid, _reason text, _force boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_authorised(_action text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_current_version(_route_id uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_detail(_route_id uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_eligibility(_route_id uuid, _driver_user_id uuid, _vehicle_id uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_link_dispatch_job(_route_id uuid, _stop_id uuid, _dispatch_job_id uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_log_event(_route_id uuid, _stop_id uuid, _version_id uuid, _event_type text, _from text, _to text, _reason text, _metadata jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_new_version(_route_id uuid, _reason text, _optimization_source text, _manual_override boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_optimization_apply(_run_id uuid, _ordered_stop_ids uuid[], _response jsonb, _reason text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_optimize(_route_id uuid, _provider_key text, _request jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_record_deviation(_route_id uuid, _stop_id uuid, _kind text, _severity text, _narrative text, _distance_m numeric) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_reorder_stops(_route_id uuid, _stop_ids uuid[], _reason text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_resolve_deviation(_deviation_id uuid, _status text, _note text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_transition(_route_id uuid, _to_status text, _reason text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_route_upsert(_route_id uuid, _payload jsonb, _reason text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_stop_attach_package(_stop_id uuid, _package_id uuid, _role text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_stop_detach_package(_link_id uuid, _reason text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_stop_remove(_stop_id uuid, _reason text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_stop_transition(_stop_id uuid, _to_status text, _reason text, _lat numeric, _lng numeric) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.logistics_stop_upsert(_stop_id uuid, _route_id uuid, _payload jsonb) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.logistics_delivery_authorised(_action text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_authorised(_action text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_current_version(_route_id uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_detail(_route_id uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_eligibility(_route_id uuid, _driver_user_id uuid, _vehicle_id uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_assign(_route_id uuid, _driver_user_id uuid, _vehicle_id uuid, _reason text, _force boolean) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_new_version(_route_id uuid, _reason text, _optimization_source text, _manual_override boolean) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_optimize(_route_id uuid, _provider_key text, _request jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_optimization_apply(_run_id uuid, _ordered_stop_ids uuid[], _response jsonb, _reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_record_deviation(_route_id uuid, _stop_id uuid, _kind text, _severity text, _narrative text, _distance_m numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_reorder_stops(_route_id uuid, _stop_ids uuid[], _reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_resolve_deviation(_deviation_id uuid, _status text, _note text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_transition(_route_id uuid, _to_status text, _reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_upsert(_route_id uuid, _payload jsonb, _reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_stop_attach_package(_stop_id uuid, _package_id uuid, _role text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_stop_detach_package(_link_id uuid, _reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_stop_remove(_stop_id uuid, _reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_stop_transition(_stop_id uuid, _to_status text, _reason text, _lat numeric, _lng numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_stop_upsert(_stop_id uuid, _route_id uuid, _payload jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_link_dispatch_job(_route_id uuid, _stop_id uuid, _dispatch_job_id uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.logistics_route_log_event(_route_id uuid, _stop_id uuid, _version_id uuid, _event_type text, _from text, _to text, _reason text, _metadata jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public._logistics_notify(_event text, _package_id uuid, _attempt_id uuid, _return_id uuid, _otp_id uuid, _recipient text, _payload jsonb) TO service_role;