-- Governed navigation registry: draft → validate → review → approve → publish, with rollback.
CREATE TABLE public.nav_registry_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  version bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','validated','in_review','approved','published','superseded','rejected')),
  title text NOT NULL,
  notes text,
  snapshot jsonb NOT NULL,
  snapshot_hash text NOT NULL,
  validation jsonb,
  validation_passed boolean,
  is_active boolean NOT NULL DEFAULT false,
  rolled_back_from uuid REFERENCES public.nav_registry_versions(id),
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  validated_at timestamptz,
  submitted_by uuid,
  submitted_at timestamptz,
  approved_by uuid,
  approved_at timestamptz,
  published_by uuid,
  published_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX nav_registry_versions_single_active
  ON public.nav_registry_versions ((is_active)) WHERE is_active;
CREATE INDEX nav_registry_versions_status_idx ON public.nav_registry_versions (status, created_at DESC);

CREATE TABLE public.nav_registry_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  version_id uuid NOT NULL REFERENCES public.nav_registry_versions(id) ON DELETE CASCADE,
  action text NOT NULL,
  from_status text,
  to_status text,
  actor uuid DEFAULT auth.uid(),
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX nav_registry_audit_version_idx ON public.nav_registry_audit (version_id, created_at DESC);

GRANT SELECT ON public.nav_registry_versions TO authenticated;
GRANT ALL ON public.nav_registry_versions TO service_role;
GRANT SELECT ON public.nav_registry_audit TO authenticated;
GRANT ALL ON public.nav_registry_audit TO service_role;

ALTER TABLE public.nav_registry_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nav_registry_audit ENABLE ROW LEVEL SECURITY;

CREATE POLICY "nav registry readable by platform admins"
  ON public.nav_registry_versions FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'super_admin') OR public.has_role(auth.uid(), 'compliance_admin'));

CREATE POLICY "nav registry audit readable by platform admins"
  ON public.nav_registry_audit FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'super_admin') OR public.has_role(auth.uid(), 'compliance_admin'));

-- Writes only through the governed RPCs below (no direct INSERT/UPDATE/DELETE policies).

CREATE OR REPLACE FUNCTION public.nav_registry_can_author(_uid uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.has_role(_uid, 'admin') OR public.has_role(_uid, 'super_admin');
$$;

CREATE OR REPLACE FUNCTION public.nav_registry_can_approve(_uid uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.has_role(_uid, 'super_admin');
$$;

CREATE OR REPLACE FUNCTION public.nav_registry_log(_version uuid, _action text, _from text, _to text, _detail jsonb)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  INSERT INTO public.nav_registry_audit (version_id, action, from_status, to_status, detail)
  VALUES (_version, _action, _from, _to, COALESCE(_detail, '{}'::jsonb));
$$;

CREATE OR REPLACE FUNCTION public.nav_registry_create_draft(
  _title text, _snapshot jsonb, _snapshot_hash text, _notes text DEFAULT NULL
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_id uuid;
BEGIN
  IF NOT public.nav_registry_can_author(auth.uid()) THEN
    RAISE EXCEPTION 'not_authorized: navigation registry authoring requires platform admin';
  END IF;
  IF _title IS NULL OR length(btrim(_title)) < 3 THEN
    RAISE EXCEPTION 'validation_failed: title must be at least 3 characters';
  END IF;
  IF _snapshot IS NULL OR jsonb_typeof(_snapshot) <> 'object' THEN
    RAISE EXCEPTION 'validation_failed: snapshot must be a JSON object';
  END IF;
  IF _snapshot_hash IS NULL OR length(_snapshot_hash) < 8 THEN
    RAISE EXCEPTION 'validation_failed: snapshot_hash missing';
  END IF;
  INSERT INTO public.nav_registry_versions (title, notes, snapshot, snapshot_hash)
  VALUES (btrim(_title), _notes, _snapshot, _snapshot_hash)
  RETURNING id INTO v_id;
  PERFORM public.nav_registry_log(v_id, 'draft_created', NULL, 'draft', jsonb_build_object('hash', _snapshot_hash));
  RETURN v_id;
END; $$;

CREATE OR REPLACE FUNCTION public.nav_registry_record_validation(
  _version_id uuid, _report jsonb
) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_from text; v_passed boolean;
BEGIN
  IF NOT public.nav_registry_can_author(auth.uid()) THEN
    RAISE EXCEPTION 'not_authorized: navigation registry validation requires platform admin';
  END IF;
  SELECT status INTO v_from FROM public.nav_registry_versions WHERE id = _version_id;
  IF v_from IS NULL THEN RAISE EXCEPTION 'not_found: version'; END IF;
  IF v_from NOT IN ('draft','validated','in_review') THEN
    RAISE EXCEPTION 'invalid_transition: cannot re-validate a % version', v_from;
  END IF;
  v_passed := COALESCE((_report->>'passed')::boolean, false);
  UPDATE public.nav_registry_versions
     SET validation = _report, validation_passed = v_passed, validated_at = now(),
         status = CASE WHEN v_passed THEN 'validated' ELSE 'draft' END, updated_at = now()
   WHERE id = _version_id;
  PERFORM public.nav_registry_log(_version_id, 'validated', v_from,
    CASE WHEN v_passed THEN 'validated' ELSE 'draft' END, _report);
  RETURN CASE WHEN v_passed THEN 'validated' ELSE 'draft' END;
END; $$;

CREATE OR REPLACE FUNCTION public.nav_registry_submit_for_review(_version_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_from text; v_passed boolean;
BEGIN
  IF NOT public.nav_registry_can_author(auth.uid()) THEN
    RAISE EXCEPTION 'not_authorized: navigation registry review submission requires platform admin';
  END IF;
  SELECT status, validation_passed INTO v_from, v_passed FROM public.nav_registry_versions WHERE id = _version_id;
  IF v_from IS NULL THEN RAISE EXCEPTION 'not_found: version'; END IF;
  IF v_from <> 'validated' THEN RAISE EXCEPTION 'invalid_transition: only a validated version can enter review'; END IF;
  IF NOT COALESCE(v_passed, false) THEN RAISE EXCEPTION 'validation_failed: integrity gates must pass before review'; END IF;
  UPDATE public.nav_registry_versions
     SET status = 'in_review', submitted_by = auth.uid(), submitted_at = now(), updated_at = now()
   WHERE id = _version_id;
  PERFORM public.nav_registry_log(_version_id, 'submitted_for_review', v_from, 'in_review', '{}'::jsonb);
END; $$;

CREATE OR REPLACE FUNCTION public.nav_registry_decide(_version_id uuid, _approve boolean, _reason text DEFAULT NULL)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_from text; v_author uuid; v_passed boolean; v_to text;
BEGIN
  IF NOT public.nav_registry_can_approve(auth.uid()) THEN
    RAISE EXCEPTION 'not_authorized: navigation registry approval requires super admin';
  END IF;
  SELECT status, created_by, validation_passed INTO v_from, v_author, v_passed
    FROM public.nav_registry_versions WHERE id = _version_id;
  IF v_from IS NULL THEN RAISE EXCEPTION 'not_found: version'; END IF;
  IF v_from <> 'in_review' THEN RAISE EXCEPTION 'invalid_transition: only an in_review version can be decided'; END IF;
  IF _approve AND v_author = auth.uid() THEN
    RAISE EXCEPTION 'separation_of_duties: the author of a navigation change cannot approve it';
  END IF;
  IF _approve AND NOT COALESCE(v_passed, false) THEN
    RAISE EXCEPTION 'validation_failed: integrity gates must pass before approval';
  END IF;
  v_to := CASE WHEN _approve THEN 'approved' ELSE 'rejected' END;
  UPDATE public.nav_registry_versions
     SET status = v_to,
         approved_by = CASE WHEN _approve THEN auth.uid() ELSE approved_by END,
         approved_at = CASE WHEN _approve THEN now() ELSE approved_at END,
         notes = COALESCE(_reason, notes), updated_at = now()
   WHERE id = _version_id;
  PERFORM public.nav_registry_log(_version_id, CASE WHEN _approve THEN 'approved' ELSE 'rejected' END,
    v_from, v_to, jsonb_build_object('reason', _reason));
  RETURN v_to;
END; $$;

CREATE OR REPLACE FUNCTION public.nav_registry_publish(_version_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_from text; v_passed boolean; v_prev uuid;
BEGIN
  IF NOT public.nav_registry_can_approve(auth.uid()) THEN
    RAISE EXCEPTION 'not_authorized: publishing navigation requires super admin';
  END IF;
  SELECT status, validation_passed INTO v_from, v_passed FROM public.nav_registry_versions WHERE id = _version_id;
  IF v_from IS NULL THEN RAISE EXCEPTION 'not_found: version'; END IF;
  IF v_from <> 'approved' THEN RAISE EXCEPTION 'invalid_transition: only an approved version can be published'; END IF;
  IF NOT COALESCE(v_passed, false) THEN RAISE EXCEPTION 'validation_failed: integrity gates must pass before publishing'; END IF;

  SELECT id INTO v_prev FROM public.nav_registry_versions WHERE is_active;
  IF v_prev IS NOT NULL THEN
    UPDATE public.nav_registry_versions SET is_active = false, status = 'superseded', updated_at = now() WHERE id = v_prev;
    PERFORM public.nav_registry_log(v_prev, 'superseded', 'published', 'superseded', jsonb_build_object('by_version', _version_id));
  END IF;

  UPDATE public.nav_registry_versions
     SET status = 'published', is_active = true, published_by = auth.uid(), published_at = now(), updated_at = now()
   WHERE id = _version_id;
  PERFORM public.nav_registry_log(_version_id, 'published', v_from, 'published', jsonb_build_object('previous', v_prev));
END; $$;

-- One-click rollback: clone a previously published snapshot into a new, already
-- approved version and activate it. The failed version is superseded, never edited.
CREATE OR REPLACE FUNCTION public.nav_registry_rollback(_to_version_id uuid, _reason text DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_src record; v_new uuid; v_active uuid;
BEGIN
  IF NOT public.nav_registry_can_approve(auth.uid()) THEN
    RAISE EXCEPTION 'not_authorized: rollback requires super admin';
  END IF;
  SELECT * INTO v_src FROM public.nav_registry_versions WHERE id = _to_version_id;
  IF v_src.id IS NULL THEN RAISE EXCEPTION 'not_found: version'; END IF;
  IF v_src.published_at IS NULL THEN
    RAISE EXCEPTION 'invalid_rollback: only a previously published version can be restored';
  END IF;
  IF v_src.is_active THEN RAISE EXCEPTION 'invalid_rollback: that version is already active'; END IF;

  SELECT id INTO v_active FROM public.nav_registry_versions WHERE is_active;
  IF v_active IS NOT NULL THEN
    UPDATE public.nav_registry_versions SET is_active = false, status = 'superseded', updated_at = now() WHERE id = v_active;
    PERFORM public.nav_registry_log(v_active, 'rolled_back', 'published', 'superseded', jsonb_build_object('reason', _reason));
  END IF;

  INSERT INTO public.nav_registry_versions
    (title, notes, snapshot, snapshot_hash, validation, validation_passed, status,
     is_active, rolled_back_from, approved_by, approved_at, published_by, published_at)
  VALUES
    ('Rollback to v' || v_src.version || ' — ' || v_src.title, _reason, v_src.snapshot, v_src.snapshot_hash,
     v_src.validation, v_src.validation_passed, 'published',
     true, v_src.id, auth.uid(), now(), auth.uid(), now())
  RETURNING id INTO v_new;

  PERFORM public.nav_registry_log(v_new, 'published_via_rollback', NULL, 'published',
    jsonb_build_object('restored_from', v_src.id, 'restored_version', v_src.version, 'reason', _reason));
  RETURN v_new;
END; $$;

REVOKE ALL ON FUNCTION public.nav_registry_create_draft(text, jsonb, text, text) FROM anon;
REVOKE ALL ON FUNCTION public.nav_registry_record_validation(uuid, jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.nav_registry_submit_for_review(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.nav_registry_decide(uuid, boolean, text) FROM anon;
REVOKE ALL ON FUNCTION public.nav_registry_publish(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.nav_registry_rollback(uuid, text) FROM anon;