CREATE INDEX IF NOT EXISTS rec_vacancies_public_slug_published_idx
  ON public.rec_vacancies (public_slug)
  WHERE approval_status = 'approved'
    AND publication_status = 'published'
    AND status = 'open'
    AND published_at IS NOT NULL;

CREATE OR REPLACE FUNCTION public.rec_public_vacancy(p_slug text)
 RETURNS TABLE(id uuid, public_slug text, vacancy_no text, title text, public_summary text, location text, employment_type text, work_arrangement text, headcount integer, required_skills text[], preferred_skills text[], qualifications text[], responsibilities text[], min_years_experience numeric, target_hire_date date, published_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT v.id, v.public_slug, v.vacancy_no, v.title, v.public_summary,
         v.location, v.employment_type, v.work_arrangement, v.headcount,
         v.required_skills, v.preferred_skills, v.qualifications,
         v.responsibilities, v.min_years_experience, v.target_hire_date,
         v.published_at
  FROM public.rec_vacancies v
  WHERE v.public_slug = p_slug
    AND v.approval_status = 'approved'
    AND v.publication_status = 'published'
    AND v.status = 'open'
    AND v.published_at IS NOT NULL
  LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.rec_apply_failure_class(p_message text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    WHEN p_message IS NULL OR btrim(p_message) = '' THEN 'TECHNICAL_FAILURE'
    WHEN p_message ~* 'missing mandatory documents|document(s)? (is|are)? ?required|Missing:' THEN 'BUSINESS_VALIDATION'
    -- A named requirement refused at the gate ("KCSE Certificate is required")
    -- is business validation: the endpoint answered correctly and quickly.
    WHEN p_message ~* '(certificate|transcript|cv|curriculum vitae|photo|letter|document|result slip)[^.]{0,40}\s(is|are)\s+required' THEN 'BUSINESS_VALIDATION'
    WHEN p_message ~* 'already applied|duplicate' THEN 'BUSINESS_VALIDATION'
    WHEN p_message ~* 'no longer open|not published|closed|deadline' THEN 'BUSINESS_VALIDATION'
    WHEN p_message ~* 'file type is not accepted|1[05] MB|exceeded the maximum allowed size|appears to be empty|format is invalid|enter a valid' THEN 'CANDIDATE_ACTION_REQUIRED'
    WHEN p_message ~* 'permission denied|not authoris|not authoriz|jwt|row-level security' THEN 'SECURITY_FAILURE'
    WHEN p_message ~* 'failed to fetch|network|timeout|timed out|502|503|504|connection' THEN 'TECHNICAL_FAILURE'
    ELSE 'TECHNICAL_FAILURE'
  END;
$function$;

UPDATE public.rec_application_remediation_cases c
   SET status = 'COMPLETED',
       resolution = 'Synthetic QA probe (vacancy VAC-QA-MATRIX, paused): generated by the careers contract matrix test, not a real candidate. Closed by remediation review; no candidate impact.',
       completed_at = now(),
       updated_at = now()
 WHERE c.status = 'OPEN'
   AND c.vacancy_slug = 'qa-application-matrix-probe'
   AND c.email LIKE '%@yalla.test';