ALTER TABLE public.location_history_202606 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_history_202607 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_history_202608 ENABLE ROW LEVEL SECURITY;