/**
 * PHASE 9 (b) — ADVERSARIAL RPC AUTHORIZATION FUZZ SUITE.
 *
 * For every SECURITY DEFINER RPC the suite asserts two things:
 *   1. WHICH ROLES MAY CALL IT (authorization), and
 *   2. WHICH RECORDS THE CALL MAY AFFECT (scope).
 *
 * Attacks are generated by mutating the request: tenant substitution, actor
 * substitution, state tampering, target substitution, replay, and privilege
 * escalation. The suite executes against a REFERENCE AUTHORIZATION KERNEL that
 * encodes exactly the checks the RPC bodies must perform — so a failure here is
 * a design defect. It is not, and is never reported as, database enforcement.
 */
import type { RlsRole } from "./rlsMatrix";

export type RpcName =
  | "logistics_book_shipment"
  | "logistics_accept_quote"
  | "logistics_create_dispatch_job"
  | "logistics_accept_dispatch_job"
  | "logistics_transition"
  | "logistics_submit_pod"
  | "logistics_open_return"
  | "logistics_open_claim"
  | "logistics_append_event"
  | "logistics_evaluate_dispatch_eligibility";

export const RPC_CALLER_ROLES: Record<RpcName, RlsRole[]> = {
  logistics_book_shipment: ["customer", "corporate_user", "corporate_admin", "operations", "super_admin"],
  logistics_accept_quote: ["customer", "corporate_admin", "super_admin"],
  logistics_create_dispatch_job: ["dispatcher", "operations", "super_admin"],
  logistics_accept_dispatch_job: ["courier", "partner_admin", "super_admin"],
  logistics_transition: ["dispatcher", "operations", "courier", "super_admin"],
  logistics_submit_pod: ["courier", "super_admin"],
  logistics_open_return: ["customer", "corporate_admin", "support", "operations", "super_admin"],
  logistics_open_claim: ["customer", "corporate_admin", "support", "compliance_officer", "super_admin"],
  logistics_append_event: ["service_role", "background_worker", "webhook_service"],
  logistics_evaluate_dispatch_eligibility: ["dispatcher", "operations", "compliance_officer", "super_admin"],
};

export interface RpcCaller {
  role: RlsRole;
  user_id: string;
  corporate_account_id: string | null;
  partner_id: string | null;
  courier_id: string | null;
}

export interface RpcTarget {
  /** Tenant that actually owns the target row on the server. */
  owner_corporate_account_id: string | null;
  owner_user_id: string;
  partner_id: string | null;
  assigned_courier_id: string | null;
  current_state: string;
  terminal: boolean;
  sealed?: boolean;
}

export interface RpcRequest {
  rpc: RpcName;
  caller: RpcCaller;
  /** Client-supplied parameters — always untrusted. */
  params: {
    target_id: string;
    /** Attacker-supplied tenant/actor overrides that MUST be ignored. */
    corporate_account_id?: string | null;
    partner_id?: string | null;
    courier_id?: string | null;
    actor_id?: string | null;
    to_state?: string;
    expected_current_state?: string;
    idempotency_key?: string | null;
  };
  target: RpcTarget;
  seenKeys?: Set<string>;
}

export type RpcRejection =
  | "not_authorised_role"
  | "cross_tenant_denied"
  | "actor_substitution_ignored_and_denied"
  | "not_assigned"
  | "illegal_transition"
  | "state_conflict"
  | "terminal_locked"
  | "already_sealed"
  | "idempotency_key_required"
  | "replayed";

export interface RpcOutcome {
  ok: boolean;
  rejection?: RpcRejection;
  /** Server-derived values actually used, proving client input was ignored. */
  effective?: { tenant: string | null; actor: string; partner: string | null; courier: string | null };
  replay?: boolean;
}

const LEGAL_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["CONFIRMED", "CANCELLED"],
  CONFIRMED: ["IN_EXECUTION", "CANCELLED"],
  IN_EXECUTION: ["DELIVERED", "PARTIALLY_DELIVERED", "FAILED", "RETURNED"],
  OFFERED: ["ACCEPTED", "EXPIRED", "REJECTED"],
  ACCEPTED: ["EN_ROUTE", "REASSIGNED"],
  EN_ROUTE: ["ARRIVED", "FAILED"],
  ARRIVED: ["DELIVERED", "FAILED"],
  DELIVERED: [],
  FAILED: [],
};

/**
 * Reference kernel: the authorization the RPC body must perform.
 * Every identity is derived server-side; client-supplied identity is discarded.
 */
export function executeRpc(req: RpcRequest): RpcOutcome {
  const { rpc, caller, params, target } = req;

  if (!RPC_CALLER_ROLES[rpc].includes(caller.role)) {
    return { ok: false, rejection: "not_authorised_role" };
  }

  // Identity is derived from the session, never from params.
  const effective = {
    tenant: caller.corporate_account_id,
    actor: caller.user_id,
    partner: caller.partner_id,
    courier: caller.courier_id,
  };

  if (params.actor_id && params.actor_id !== caller.user_id && caller.role !== "super_admin" && caller.role !== "service_role") {
    return { ok: false, rejection: "actor_substitution_ignored_and_denied", effective };
  }

  const privileged = caller.role === "super_admin" || caller.role === "service_role";

  // Tenant scope.
  if (!privileged) {
    if (["customer", "corporate_user", "corporate_admin"].includes(caller.role)) {
      const owns =
        target.owner_user_id === caller.user_id ||
        (!!target.owner_corporate_account_id && target.owner_corporate_account_id === caller.corporate_account_id);
      if (!owns) return { ok: false, rejection: "cross_tenant_denied", effective };
    }
    if (caller.role === "partner_admin" && target.partner_id !== caller.partner_id) {
      return { ok: false, rejection: "cross_tenant_denied", effective };
    }
    if (caller.role === "courier" && target.assigned_courier_id !== caller.courier_id) {
      return { ok: false, rejection: "not_assigned", effective };
    }
  }

  // Idempotency.
  const mutating = rpc !== "logistics_evaluate_dispatch_eligibility";
  if (mutating) {
    if (!params.idempotency_key) return { ok: false, rejection: "idempotency_key_required", effective };
    if (req.seenKeys?.has(params.idempotency_key)) return { ok: true, replay: true, effective };
  }

  if (rpc === "logistics_submit_pod" && target.sealed) {
    return { ok: false, rejection: "already_sealed", effective };
  }

  // State authority.
  if (params.to_state) {
    if (target.terminal) return { ok: false, rejection: "terminal_locked", effective };
    if (params.expected_current_state && params.expected_current_state !== target.current_state) {
      return { ok: false, rejection: "state_conflict", effective };
    }
    const legal = LEGAL_TRANSITIONS[target.current_state] ?? [];
    if (!legal.includes(params.to_state)) return { ok: false, rejection: "illegal_transition", effective };
  }

  if (mutating && params.idempotency_key) req.seenKeys?.add(params.idempotency_key);
  return { ok: true, effective };
}

/* ---------------------------------- fuzzing ---------------------------------- */

export type FuzzMutation =
  | "BASELINE"
  | "UNAUTHORISED_ROLE"
  | "TENANT_SUBSTITUTION"
  | "ACTOR_SUBSTITUTION"
  | "TARGET_SUBSTITUTION"
  | "STATE_TAMPERING"
  | "STALE_EXPECTED_STATE"
  | "TERMINAL_REOPEN"
  | "MISSING_IDEMPOTENCY"
  | "REPLAY"
  | "PARTNER_SUBSTITUTION"
  | "COURIER_SUBSTITUTION";

export interface FuzzCase {
  id: string;
  rpc: RpcName;
  mutation: FuzzMutation;
  role: RlsRole;
  expected: "ALLOW" | "DENY" | "REPLAY";
  actual: "ALLOW" | "DENY" | "REPLAY";
  rejection?: RpcRejection;
  /** Records the call was permitted to affect. */
  affected: string[];
  passed: boolean;
}

const caller = (role: RlsRole, over: Partial<RpcCaller> = {}): RpcCaller => ({
  role,
  user_id: "user-a",
  corporate_account_id: "corp-a",
  partner_id: "partner-a",
  courier_id: "courier-a",
  ...over,
});

const target = (over: Partial<RpcTarget> = {}): RpcTarget => ({
  owner_corporate_account_id: "corp-a",
  owner_user_id: "user-a",
  partner_id: "partner-a",
  assigned_courier_id: "courier-a",
  current_state: "IN_EXECUTION",
  terminal: false,
  ...over,
});

const PRIMARY_ROLE: Record<RpcName, RlsRole> = {
  logistics_book_shipment: "customer",
  logistics_accept_quote: "customer",
  logistics_create_dispatch_job: "dispatcher",
  logistics_accept_dispatch_job: "courier",
  logistics_transition: "operations",
  logistics_submit_pod: "courier",
  logistics_open_return: "customer",
  logistics_open_claim: "customer",
  logistics_append_event: "service_role",
  logistics_evaluate_dispatch_eligibility: "operations",
};

export function runRpcFuzzSuite(): FuzzCase[] {
  const cases: FuzzCase[] = [];
  let n = 0;

  const add = (
    rpc: RpcName,
    mutation: FuzzMutation,
    role: RlsRole,
    expected: FuzzCase["expected"],
    build: () => RpcRequest,
  ) => {
    const req = build();
    const out = executeRpc(req);
    const actual: FuzzCase["actual"] = out.replay ? "REPLAY" : out.ok ? "ALLOW" : "DENY";
    n += 1;
    cases.push({
      id: `FZ-${String(n).padStart(3, "0")}`,
      rpc,
      mutation,
      role,
      expected,
      actual,
      rejection: out.rejection,
      affected: actual === "ALLOW" ? [req.params.target_id] : [],
      passed: actual === expected,
    });
  };

  for (const rpc of Object.keys(RPC_CALLER_ROLES) as RpcName[]) {
    const role = PRIMARY_ROLE[rpc];
    const base = (over: Partial<RpcRequest["params"]> = {}, t: Partial<RpcTarget> = {}, c: Partial<RpcCaller> = {}): RpcRequest => ({
      rpc,
      caller: caller(role, c),
      params: { target_id: "row-1", idempotency_key: `k-${rpc}-${Math.random().toString(36).slice(2)}`, ...over },
      target: target(t),
      seenKeys: new Set<string>(),
    });

    add(rpc, "BASELINE", role, "ALLOW", () => base());
    add(rpc, "UNAUTHORISED_ROLE", "anonymous", "DENY", () => ({ ...base(), caller: caller("anonymous") }));
    // Tenant-scoped roles must be denied; staff and service identities are
    // platform-wide by design, so the tenant swap is legitimately allowed.
    const tenantScoped = ["customer", "corporate_user", "corporate_admin", "partner_admin"].includes(role);
    const privileged = role === "service_role" || role === "super_admin";
    add(rpc, "TENANT_SUBSTITUTION", role, tenantScoped ? "DENY" : "ALLOW", () =>
      base({ corporate_account_id: "corp-b" }, { owner_corporate_account_id: "corp-b", owner_user_id: "user-b" }));
    add(rpc, "ACTOR_SUBSTITUTION", role, privileged ? "ALLOW" : "DENY", () => base({ actor_id: "user-b" }));
    add(rpc, "PARTNER_SUBSTITUTION", "partner_admin", RPC_CALLER_ROLES[rpc].includes("partner_admin") ? "DENY" : "DENY", () => ({
      ...base({ partner_id: "partner-b" }, { partner_id: "partner-b" }),
      caller: caller("partner_admin"),
    }));
    add(rpc, "COURIER_SUBSTITUTION", "courier", "DENY", () => ({
      ...base({ courier_id: "courier-b" }, { assigned_courier_id: "courier-b" }),
      caller: caller("courier"),
    }));
    add(rpc, "MISSING_IDEMPOTENCY", role, rpc === "logistics_evaluate_dispatch_eligibility" ? "ALLOW" : "DENY", () =>
      base({ idempotency_key: null }));
    add(rpc, "REPLAY", role, rpc === "logistics_evaluate_dispatch_eligibility" ? "ALLOW" : "REPLAY", () => {
      const req = base({ idempotency_key: "fixed-key" });
      executeRpc(req);
      return req;
    });
  }

  // Transition-specific attacks.
  const tRole: RlsRole = "operations";
  add("logistics_transition", "STATE_TAMPERING", tRole, "DENY", () => ({
    rpc: "logistics_transition",
    caller: caller(tRole),
    params: { target_id: "row-1", to_state: "SETTLED", idempotency_key: "t1" },
    target: target(),
    seenKeys: new Set(),
  }));
  add("logistics_transition", "STALE_EXPECTED_STATE", tRole, "DENY", () => ({
    rpc: "logistics_transition",
    caller: caller(tRole),
    params: { target_id: "row-1", to_state: "DELIVERED", expected_current_state: "CONFIRMED", idempotency_key: "t2" },
    target: target({ current_state: "IN_EXECUTION" }),
    seenKeys: new Set(),
  }));
  add("logistics_transition", "TERMINAL_REOPEN", tRole, "DENY", () => ({
    rpc: "logistics_transition",
    caller: caller(tRole),
    params: { target_id: "row-1", to_state: "IN_EXECUTION", idempotency_key: "t3" },
    target: target({ current_state: "DELIVERED", terminal: true }),
    seenKeys: new Set(),
  }));
  add("logistics_submit_pod", "TERMINAL_REOPEN", "courier", "DENY", () => ({
    rpc: "logistics_submit_pod",
    caller: caller("courier"),
    params: { target_id: "pod-1", idempotency_key: "p1" },
    target: target({ sealed: true }),
    seenKeys: new Set(),
  }));

  return cases;
}

export interface RpcFuzzSummary {
  rpcs: number;
  cases: number;
  denials: number;
  failures: FuzzCase[];
  /** Reference-kernel verdict. Database enforcement remains BLOCKED. */
  modelStatus: "PASS" | "FAIL";
  databaseStatus: "BLOCKED";
  callerMatrix: Record<RpcName, RlsRole[]>;
}

export function rpcFuzzSummary(): RpcFuzzSummary {
  const cases = runRpcFuzzSuite();
  const failures = cases.filter((c) => !c.passed);
  return {
    rpcs: Object.keys(RPC_CALLER_ROLES).length,
    cases: cases.length,
    denials: cases.filter((c) => c.actual === "DENY").length,
    failures,
    modelStatus: failures.length === 0 ? "PASS" : "FAIL",
    databaseStatus: "BLOCKED",
    callerMatrix: RPC_CALLER_ROLES,
  };
}
