/**
 * STAGE 9 — COMMERCIAL BOOK.
 *
 * End-to-end management of the commercial chain: accounts, opportunities,
 * proposals, contracts and service orders. Prices come only from the published
 * rate card; references and account links are generated by the database.
 */
import * as React from "react";
import { Link, useSearchParams } from "react-router-dom";
import {
  Banknote,
  Building2,
  CalendarCheck,
  Compass,
  FileSignature,
  FileText,
  Loader2,
  PackageCheck,
  Plus,
  RefreshCw,
  Target,
  Truck,
} from "lucide-react";
import { BillingPanel } from "@/components/staff/workspace/BillingPanel";
import { ServiceFeedPanel } from "@/components/staff/workspace/ServiceFeedPanel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { handoffToService, requestApproval } from "@/lib/workspace/approvals";
import { Textarea } from "@/components/ui/textarea";
import { WorkspaceEmptyState } from "@/components/staff/workspace/WorkspaceEmptyState";
import { useToast } from "@/hooks/use-toast";
import type { NewAccount } from "@/lib/crm/api";
import type { AccountLifecycleStage, CrmAccount } from "@/lib/crm/types";
import { ACCOUNT_LIFECYCLE_STAGES } from "@/lib/crm/types";
import {
  OPPORTUNITY_STAGES,
  advanceOpportunity,
  createBookAccount,
  createBookContract,
  createBookOpportunity,
  createBookQuotation,
  linesFor,
  listBookAccounts,
  listBookContracts,
  listBookOpportunities,
  listBookQuotations,
  listBookSchedules,
  listContractTemplates,
  loadRateCard,
  money,
  moneyFromCents,
  serviceCodesOf,
  updateContractStatus,
  type BookContract,
  type BookOpportunity,
  type BookQuotation,
  type BookSchedule,
  type ContractTemplate,
  type OpportunityStage,
  type RateCard,
} from "@/lib/workspace/commercialBook";
import { ReadingBadge } from "@/components/staff/workspace/ReadingBadge";
import { opportunityHealth, proposalMomentum, renewalRisk } from "@/lib/workspace/commercialIntelligence";
import { NextBestActionQueue } from "@/components/staff/workspace/NextBestActionQueue";
import { BookAssistant } from "@/components/staff/workspace/BookAssistant";
import { BookDailyClose } from "@/components/staff/workspace/BookDailyClose";
import { buildNextBestActions, queueHeadline, type NextBestAction } from "@/lib/intelligence/nextBestAction";
import { loadInspection, type InspectionRow } from "@/lib/intelligence/pipelineInspection";
import { listSignals, setSignalStatus, type CommercialSignal } from "@/lib/intelligence/signals";
import { fetchSalesDayClose, type SalesDayClose } from "@/lib/sales/dayClose";


const date = (iso: string | null): string => {
  if (!iso) return "—";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
};

interface BookData {
  accounts: CrmAccount[];
  opportunities: BookOpportunity[];
  quotations: BookQuotation[];
  contracts: BookContract[];
  schedules: BookSchedule[];
  templates: ContractTemplate[];
  card: RateCard | null;
}

const EMPTY: BookData = {
  accounts: [],
  opportunities: [],
  quotations: [],
  contracts: [],
  schedules: [],
  templates: [],
  card: null,
};

export default function CommercialBook() {
  const { toast } = useToast();
  const [data, setData] = React.useState<BookData>(EMPTY);
  const [loading, setLoading] = React.useState(true);
  const [refused, setRefused] = React.useState<string | null>(null);

  const load = React.useCallback(async () => {
    setLoading(true);
    try {
      const [accounts, opportunities, quotations, contracts, schedules, templates, card] = await Promise.all([
        listBookAccounts(),
        listBookOpportunities(),
        listBookQuotations(),
        listBookContracts(),
        listBookSchedules(),
        listContractTemplates(),
        loadRateCard(),
      ]);
      setData({ accounts, opportunities, quotations, contracts, schedules, templates, card });
      setRefused(null);
    } catch (e) {
      setRefused(e instanceof Error ? e.message : "The commercial book could not be read.");
    }
    setLoading(false);
  }, []);

  React.useEffect(() => {
    void load();
  }, [load]);

  /* ---------------- intelligence layer over the same records ---------------- */
  const [params, setParams] = useSearchParams();
  const tab = params.get("tab") ?? "next";
  const setTab = (next: string) => {
    const p = new URLSearchParams(params);
    if (next === "next") p.delete("tab");
    else p.set("tab", next);
    setParams(p, { replace: true });
  };

  const [rows, setRows] = React.useState<InspectionRow[]>([]);
  const [signals, setSignals] = React.useState<CommercialSignal[]>([]);
  const [close, setClose] = React.useState<SalesDayClose | null>(null);
  const [intelLoading, setIntelLoading] = React.useState(true);
  const [busyKey, setBusyKey] = React.useState<string | null>(null);

  const loadIntel = React.useCallback(async () => {
    setIntelLoading(true);
    const [inspection, open, dayClose] = await Promise.all([
      loadInspection(7).catch(() => ({ rows: [] as InspectionRow[], changesAvailable: false })),
      listSignals({ statuses: ["open", "acknowledged"], limit: 200 }).catch(() => [] as CommercialSignal[]),
      fetchSalesDayClose(null, false).catch(() => null),
    ]);
    setRows(inspection.rows);
    setSignals(open);
    setClose(dayClose);
    setIntelLoading(false);
  }, []);

  React.useEffect(() => {
    void loadIntel();
  }, [loadIntel]);

  const actions: NextBestAction[] = React.useMemo(
    () => buildNextBestActions({ rows, signals, limit: 12 }),
    [rows, signals],
  );

  const acceptAction = async (action: NextBestAction) => {
    setBusyKey(action.key);
    try {
      if (action.signalId) {
        await setSignalStatus(action.signalId, "actioned", "Recorded as done from the next best action queue.");
      }
      toast({ title: "Recorded", description: action.action });
      await loadIntel();
    } catch (e) {
      toast({
        title: "Not recorded",
        description: e instanceof Error ? e.message : "This could not be recorded.",
        variant: "destructive",
      });
    }
    setBusyKey(null);
  };

  const fail = (e: unknown) =>
    toast({
      title: "Not saved",
      description: e instanceof Error ? e.message : "The record could not be saved.",
      variant: "destructive",
    });

  const accountName = (id: string | null) =>
    data.accounts.find((a) => a.id === id)?.name ?? "Account not released";

  if (loading) {
    return (
      <div className="flex items-center gap-2 p-8 text-sm text-muted-foreground">
        <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> Loading your commercial book…
      </div>
    );
  }

  if (refused) {
    return (
      <div className="p-6">
        <WorkspaceEmptyState
          title="The commercial book is not released to your account"
          message={refused}
          actions={[{ label: "Back to my work queue", to: "/staff/workspace/work-queue" }]}
        />
      </div>
    );
  }

  return (
    <div className="space-y-5 p-4 md:p-6">
      <header className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold">Commercial book</h1>
          <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
            Create and run the whole chain — customer, deal, proposal, contract, service order. Prices come from the
            published rate card{data.card ? ` (${data.card.name} v${data.card.version}, ${data.card.status})` : ""}.
          </p>
        </div>
        <Button variant="outline" onClick={() => void load()}>
          <RefreshCw className="mr-2 h-4 w-4" aria-hidden /> Refresh
        </Button>
      </header>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="flex-wrap">
          <TabsTrigger value="next">
            <Compass className="mr-1.5 h-4 w-4" aria-hidden /> Next best actions ({actions.length})
          </TabsTrigger>
          <TabsTrigger value="close">
            <CalendarCheck className="mr-1.5 h-4 w-4" aria-hidden /> Daily close
          </TabsTrigger>
          <TabsTrigger value="accounts">
            <Building2 className="mr-1.5 h-4 w-4" aria-hidden /> Accounts ({data.accounts.length})
          </TabsTrigger>
          <TabsTrigger value="opportunities">
            <Target className="mr-1.5 h-4 w-4" aria-hidden /> Opportunities ({data.opportunities.length})
          </TabsTrigger>
          <TabsTrigger value="proposals">
            <FileText className="mr-1.5 h-4 w-4" aria-hidden /> Proposals ({data.quotations.length})
          </TabsTrigger>
          <TabsTrigger value="contracts">
            <FileSignature className="mr-1.5 h-4 w-4" aria-hidden /> Contracts ({data.contracts.length})
          </TabsTrigger>
          <TabsTrigger value="orders">
            <PackageCheck className="mr-1.5 h-4 w-4" aria-hidden /> Service orders ({data.schedules.length})
          </TabsTrigger>
          <TabsTrigger value="billing">
            <Banknote className="mr-1.5 h-4 w-4" aria-hidden /> Invoices &amp; payments
          </TabsTrigger>
          <TabsTrigger value="service">
            <Truck className="mr-1.5 h-4 w-4" aria-hidden /> Service feed
          </TabsTrigger>
        </TabsList>

        {/* --------------------- invoices, payments, balances ------------------- */}
        <TabsContent value="billing" className="mt-4">
          <BillingPanel />
        </TabsContent>

        {/* --------------------- live service execution feed -------------------- */}
        <TabsContent value="service" className="mt-4">
          <ServiceFeedPanel />
        </TabsContent>

        {/* --------------------- next best actions + assistant ------------------ */}
        <TabsContent value="next" className="mt-4 space-y-4">
          <BookAssistant actions={actions} rows={rows} signals={signals} close={close} />
          <NextBestActionQueue
            actions={actions}
            headline={queueHeadline(actions)}
            loading={intelLoading}
            busyKey={busyKey}
            onAccept={(a) => void acceptAction(a)}
          />
        </TabsContent>

        {/* ----------------------------- daily close --------------------------- */}
        <TabsContent value="close" className="mt-4">
          <BookDailyClose />
        </TabsContent>


        {/* ------------------------------ accounts ----------------------------- */}
        <TabsContent value="accounts" className="mt-4 space-y-3">
          <NewAccountDialog
            onCreate={async (input) => {
              try {
                const created = await createBookAccount(input);
                toast({ title: "Account created", description: `${created.name} (${created.account_ref})` });
                await load();
                return true;
              } catch (e) {
                fail(e);
                return false;
              }
            }}
          />
          {data.accounts.length === 0 ? (
            <WorkspaceEmptyState title="No customer account yet" message="Add the first account to start the book." />
          ) : (
            <Card>
              <CardContent className="py-2">
                {data.accounts.map((a) => (
                  <div key={a.id} className="flex items-center justify-between gap-3 border-b py-3 last:border-b-0">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{a.name}</p>
                      <p className="mt-0.5 truncate text-xs text-muted-foreground">
                        {a.account_ref} · {[a.industry, a.city, a.country].filter(Boolean).join(" · ")}
                      </p>
                      <div className="mt-1.5 flex flex-wrap gap-1.5">
                        <Badge variant="secondary" className="text-[10px] capitalize">
                          {a.lifecycle_stage.replace(/_/g, " ")}
                        </Badge>
                        <Badge variant="outline" className="text-[10px] capitalize">
                          {a.importance_tier}
                        </Badge>
                      </div>
                    </div>
                    <Button size="sm" variant="outline" asChild>
                      <Link to={`/staff/workspace/accounts/${a.id}`}>Open 360</Link>
                    </Button>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* --------------------------- opportunities --------------------------- */}
        <TabsContent value="opportunities" className="mt-4 space-y-3">
          <NewOpportunityDialog
            accounts={data.accounts}
            onCreate={async (input) => {
              try {
                const res = await createBookOpportunity(input);
                toast({ title: "Opportunity created", description: res.opportunity_ref });
                await load();
                return true;
              } catch (e) {
                fail(e);
                return false;
              }
            }}
          />
          {data.opportunities.length === 0 ? (
            <WorkspaceEmptyState title="No opportunity recorded" message="Create one against an account." />
          ) : (
            <Card>
              <CardContent className="py-2">
                {data.opportunities.map((o) => (
                  <div key={o.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 last:border-b-0">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{o.title}</p>
                      <p className="mt-0.5 truncate text-xs text-muted-foreground">
                        {o.opportunity_ref} · {o.customer_label ?? "customer not named"} ·{" "}
                        {moneyFromCents(o.expected_value_cents, o.currency ?? "KES")}
                        {o.probability_pct != null ? ` · ${o.probability_pct}% likely` : ""}
                      </p>
                      <div className="mt-1.5">
                        <ReadingBadge
                          label="Health"
                          reading={opportunityHealth({
                            stage: o.stage,
                            updatedAt: o.updated_at,
                            valueCents: o.expected_value_cents,
                            probabilityPct: o.probability_pct,
                            hasProposal: data.quotations.some((q) => q.opportunity_id === o.id),
                          })}
                        />
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Select
                        value={o.stage}
                        onValueChange={(stage) => {
                          void advanceOpportunity(o.id, stage as OpportunityStage, "Commercial book")
                            .then(() => {
                              toast({ title: "Stage updated", description: `${o.opportunity_ref} → ${stage}` });
                              return load();
                            })
                            .catch(fail);
                        }}
                      >
                        <SelectTrigger className="h-8 w-[150px] text-xs capitalize">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {OPPORTUNITY_STAGES.map((s) => (
                            <SelectItem key={s} value={s} className="capitalize">
                              {s}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* ------------------------------ proposals ---------------------------- */}
        <TabsContent value="proposals" className="mt-4 space-y-3">
          <NewProposalDialog
            accounts={data.accounts}
            opportunities={data.opportunities}
            card={data.card}
            onCreate={async (input) => {
              try {
                const res = await createBookQuotation(input);
                toast({
                  title: `Proposal ${res.quote_number}`,
                  description: `${money(res.total_amount, res.currency)} on rate card v${res.rate_card_version}${
                    (res.unpriced ?? []).length > 0 ? " — some lines are not on the card and need pricing approval" : ""
                  }`,
                });
                await load();
                return true;
              } catch (e) {
                fail(e);
                return false;
              }
            }}
          />
          {data.quotations.length === 0 ? (
            <WorkspaceEmptyState title="No proposal issued" message="Build one from the published rate card." />
          ) : (
            <Card>
              <CardContent className="py-2">
                {data.quotations.map((q) => (
                  <div key={q.id} className="flex items-center justify-between gap-3 border-b py-3 last:border-b-0">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{q.quote_number}</p>
                      <p className="mt-0.5 truncate text-xs text-muted-foreground">
                        {accountName(q.account_id)} · {q.status} · valid to {date(q.valid_until)}
                      </p>
                      <div className="mt-1.5">
                        <ReadingBadge
                          label="Momentum"
                          reading={proposalMomentum({
                            status: q.status,
                            approvalStatus: q.approval_status,
                            createdAt: q.created_at,
                            validUntil: q.valid_until,
                            totalAmount: q.total_amount,
                          })}
                        />
                      </div>
                    </div>
                    <div className="flex shrink-0 items-center gap-2">
                      {q.approval_status === "required" && (
                        <Badge variant="destructive" className="text-[10px]">
                          Approval required
                        </Badge>
                      )}
                      <span className="text-sm font-semibold tabular-nums">
                        {money(q.total_amount, q.currency ?? "KES")}
                      </span>
                      {q.approval_status !== "approved" && (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => {
                            void requestApproval({ entityType: "proposal", entityId: q.id })
                              .then(() => {
                                toast({
                                  title: "Sent for approval",
                                  description: `${q.quote_number} is now with a manager.`,
                                });
                                return load();
                              })
                              .catch(fail);
                          }}
                        >
                          Send for approval
                        </Button>
                      )}
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* ------------------------------ contracts ---------------------------- */}
        <TabsContent value="contracts" className="mt-4 space-y-3">
          <NewContractDialog
            accounts={data.accounts}
            opportunities={data.opportunities}
            templates={data.templates}
            card={data.card}
            onCreate={async (input) => {
              try {
                await createBookContract(input);
                toast({ title: "Contract drafted", description: input.customerLegalName });
                await load();
                return true;
              } catch (e) {
                fail(e);
                return false;
              }
            }}
          />
          {data.contracts.length === 0 ? (
            <WorkspaceEmptyState title="No contract yet" message="Draft one from an approved template." />
          ) : (
            <Card>
              <CardContent className="py-2">
                {data.contracts.map((c) => (
                  <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 last:border-b-0">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{c.customer_legal_name}</p>
                      <p className="mt-0.5 truncate text-xs text-muted-foreground">
                        {accountName(c.account_id)} · effective {date(c.effective_date)} · {c.contract_term ?? "term not set"}
                      </p>
                      <div className="mt-1.5">
                        <ReadingBadge
                          label="Renewal"
                          reading={renewalRisk({
                            status: c.status,
                            effectiveDate: c.effective_date,
                            contractTerm: c.contract_term,
                            hasApprovedSchedule: data.schedules.some(
                              (s) => s.contract_instance_id === c.id && s.approval_status === "approved",
                            ),
                          })}
                        />
                      </div>
                      <div className="mt-1.5 flex flex-wrap gap-1.5">
                        {(c.selected_services ?? []).map((s) => (
                          <Badge key={s} variant="outline" className="text-[10px] capitalize">
                            {s.replace(/_/g, " ")}
                          </Badge>
                        ))}
                      </div>
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                    {c.status !== "active" && (
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => {
                          void requestApproval({ entityType: "contract", entityId: c.id })
                            .then(() => {
                              toast({ title: "Sent for approval", description: c.customer_legal_name });
                              return load();
                            })
                            .catch(fail);
                        }}
                      >
                        Send for approval
                      </Button>
                    )}
                    {c.status === "active" && (
                      <Button
                        size="sm"
                        onClick={() => {
                          void handoffToService({
                            contractInstanceId: c.id,
                            rateCardId: c.rate_card_id ?? data.card?.id ?? null,
                            services: c.selected_services ?? [],
                          })
                            .then((res) => {
                              toast({
                                title: "Handed over to delivery",
                                description:
                                  res.gaps.length > 0
                                    ? `Service order raised for approval. An exception was recorded: ${res.gaps.join("; ")}.`
                                    : "Service order raised for approval.",
                                variant: res.gaps.length > 0 ? "destructive" : undefined,
                              });
                              return load();
                            })
                            .catch(fail);
                        }}
                      >
                        Hand over to delivery
                      </Button>
                    )}
                    <Select
                      value={c.status}
                      onValueChange={(status) => {
                        void updateContractStatus(c.id, status)
                          .then(() => {
                            toast({ title: "Contract updated", description: `${c.customer_legal_name} → ${status}` });
                            return load();
                          })
                          .catch(fail);
                      }}
                    >
                      <SelectTrigger className="h-8 w-[150px] text-xs capitalize">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {["draft", "issued", "signed", "active", "terminated"].map((s) => (
                          <SelectItem key={s} value={s} className="capitalize">
                            {s}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* ---------------------------- service orders ------------------------- */}
        <TabsContent value="orders" className="mt-4 space-y-3">
          <NewServiceOrderDialog
            contracts={data.contracts}
            card={data.card}
            onCreate={async (input) => {
              try {
                const res = await handoffToService({
                  contractInstanceId: input.contractInstanceId,
                  rateCardId: input.rateCardId,
                  title: input.title,
                  services: input.services,
                  locations: input.locations,
                  vehicleCategories: input.vehicleCategories,
                  validity: input.validity,
                  commercialTerms: input.commercialTerms,

                });
                toast({
                  title: "Service order raised for approval",
                  description:
                    res.gaps.length > 0
                      ? `An exception was recorded: ${res.gaps.join("; ")}.`
                      : input.title,
                  variant: res.gaps.length > 0 ? "destructive" : undefined,
                });
                await load();
                return true;
              } catch (e) {
                fail(e);
                return false;
              }
            }}
          />
          {data.schedules.length === 0 ? (
            <WorkspaceEmptyState
              title="No service order yet"
              message="A service order lists the services, locations and vehicles a contract actually covers."
            />
          ) : (
            <Card>
              <CardContent className="py-2">
                {data.schedules.map((s) => {
                  const contract = data.contracts.find((c) => c.id === s.contract_instance_id);
                  return (
                    <div key={s.id} className="flex items-start justify-between gap-3 border-b py-3 last:border-b-0">
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium">{s.title}</p>
                        <p className="mt-0.5 truncate text-xs text-muted-foreground">
                          {contract?.customer_legal_name ?? "contract not released"} ·{" "}
                          {(s.services ?? []).join(", ") || "no service listed"} · {s.validity ?? "validity not set"}
                        </p>
                        <p className="mt-0.5 truncate text-xs text-muted-foreground">
                          {(s.locations ?? []).join(", ") || "no location listed"}
                        </p>
                      </div>
                      <Badge variant={s.approval_status === "approved" ? "default" : "secondary"} className="text-[10px] capitalize">
                        {s.approval_status}
                      </Badge>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}

/* ------------------------------- dialogs -------------------------------- */

function useDialog(onCreate: () => Promise<boolean>) {
  const [open, setOpen] = React.useState(false);
  const [saving, setSaving] = React.useState(false);
  const submit = async () => {
    setSaving(true);
    const ok = await onCreate();
    setSaving(false);
    if (ok) setOpen(false);
  };
  return { open, setOpen, saving, submit };
}

function NewAccountDialog({
  onCreate,
}: {
  onCreate: (input: NewAccount) => Promise<boolean>;
}) {
  const [name, setName] = React.useState("");
  const [industry, setIndustry] = React.useState("");
  const [city, setCity] = React.useState("");
  const [stage, setStage] = React.useState<AccountLifecycleStage>("prospect");
  const d = useDialog(async () => {
    if (!name.trim()) return false;
    const ok = await onCreate({
      name: name.trim(),
      industry: industry.trim() || undefined,
      city: city.trim() || undefined,
      lifecycle_stage: stage,
    });
    if (ok) {
      setName("");
      setIndustry("");
      setCity("");
    }
    return ok;
  });

  return (
    <Dialog open={d.open} onOpenChange={d.setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" aria-hidden /> New account
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>New customer account</DialogTitle>
          <DialogDescription>The reference is generated for you.</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <div>
            <Label htmlFor="acc-name">Customer name</Label>
            <Input id="acc-name" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <Label htmlFor="acc-industry">Industry</Label>
              <Input id="acc-industry" value={industry} onChange={(e) => setIndustry(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="acc-city">City</Label>
              <Input id="acc-city" value={city} onChange={(e) => setCity(e.target.value)} />
            </div>
          </div>
          <div>
            <Label>Relationship stage</Label>
            <Select value={stage} onValueChange={(v) => setStage(v as AccountLifecycleStage)}>
              <SelectTrigger className="capitalize">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {ACCOUNT_LIFECYCLE_STAGES.map((s) => (
                  <SelectItem key={s} value={s} className="capitalize">
                    {s.replace(/_/g, " ")}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <DialogFooter>
          <Button onClick={() => void d.submit()} disabled={d.saving || !name.trim()}>
            {d.saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden />} Create account
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function AccountPicker({
  accounts,
  value,
  onChange,
  label = "Account",
}: {
  accounts: CrmAccount[];
  value: string;
  onChange: (v: string) => void;
  label?: string;
}) {
  return (
    <div>
      <Label>{label}</Label>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder="Choose an account" />
        </SelectTrigger>
        <SelectContent>
          {accounts.map((a) => (
            <SelectItem key={a.id} value={a.id}>
              {a.name} · {a.account_ref}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  );
}

function NewOpportunityDialog({
  accounts,
  onCreate,
}: {
  accounts: CrmAccount[];
  onCreate: (input: {
    accountId: string;
    title: string;
    stage: OpportunityStage;
    expectedValueKes: number | null;
    probabilityPct: number | null;
  }) => Promise<boolean>;
}) {
  const [accountId, setAccountId] = React.useState("");
  const [title, setTitle] = React.useState("");
  const [stage, setStage] = React.useState<OpportunityStage>("qualified");
  const [value, setValue] = React.useState("");
  const [probability, setProbability] = React.useState("");
  const ready = !!accountId && title.trim().length > 0;
  const d = useDialog(async () => {
    if (!ready) return false;
    const ok = await onCreate({
      accountId,
      title: title.trim(),
      stage,
      expectedValueKes: value ? Number(value) : null,
      probabilityPct: probability ? Number(probability) : null,
    });
    if (ok) {
      setTitle("");
      setValue("");
      setProbability("");
    }
    return ok;
  });

  return (
    <Dialog open={d.open} onOpenChange={d.setOpen}>
      <DialogTrigger asChild>
        <Button disabled={accounts.length === 0}>
          <Plus className="mr-2 h-4 w-4" aria-hidden /> New opportunity
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>New opportunity</DialogTitle>
          <DialogDescription>Linked to the account automatically.</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <AccountPicker accounts={accounts} value={accountId} onChange={setAccountId} />
          <div>
            <Label htmlFor="opp-title">What is the opportunity?</Label>
            <Input id="opp-title" value={title} onChange={(e) => setTitle(e.target.value)} />
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div>
              <Label htmlFor="opp-value">Value (KES)</Label>
              <Input id="opp-value" type="number" min={0} value={value} onChange={(e) => setValue(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="opp-prob">Likelihood %</Label>
              <Input
                id="opp-prob"
                type="number"
                min={0}
                max={100}
                value={probability}
                onChange={(e) => setProbability(e.target.value)}
              />
            </div>
            <div>
              <Label>Stage</Label>
              <Select value={stage} onValueChange={(v) => setStage(v as OpportunityStage)}>
                <SelectTrigger className="capitalize">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {OPPORTUNITY_STAGES.map((s) => (
                    <SelectItem key={s} value={s} className="capitalize">
                      {s}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button onClick={() => void d.submit()} disabled={d.saving || !ready}>
            {d.saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden />} Create opportunity
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

interface DraftLine {
  service_code: string;
  scope_label: string;
  category_code: string;
  pricing_basis: string;
  quantity: number;
  amount: number;
}

function NewProposalDialog({
  accounts,
  opportunities,
  card,
  onCreate,
}: {
  accounts: CrmAccount[];
  opportunities: BookOpportunity[];
  card: RateCard | null;
  onCreate: (input: {
    accountId: string;
    lines: { service_code: string; scope_label: string; category_code: string; pricing_basis: string; quantity: number }[];
    opportunityId: string | null;
    validUntil: string | null;
    notes: string | null;
  }) => Promise<boolean>;
}) {
  const [accountId, setAccountId] = React.useState("");
  const [opportunityId, setOpportunityId] = React.useState("");
  const [validUntil, setValidUntil] = React.useState("");
  const [notes, setNotes] = React.useState("");
  const [service, setService] = React.useState("");
  const [lineId, setLineId] = React.useState("");
  const [quantity, setQuantity] = React.useState("1");
  const [lines, setLines] = React.useState<DraftLine[]>([]);

  const services = serviceCodesOf(card);
  const options = linesFor(card, service);
  const total = lines.reduce((s, l) => s + l.amount * l.quantity, 0);
  const ready = !!accountId && lines.length > 0;

  const addLine = () => {
    const rl = options.find((o) => o.id === lineId);
    if (!rl) return;
    setLines((prev) => [
      ...prev,
      {
        service_code: rl.service_code,
        scope_label: rl.scope_label,
        category_code: rl.category_code,
        pricing_basis: rl.pricing_basis,
        quantity: Math.max(1, Number(quantity) || 1),
        amount: Number(rl.amount),
      },
    ]);
    setLineId("");
    setQuantity("1");
  };

  const d = useDialog(async () => {
    if (!ready) return false;
    const ok = await onCreate({
      accountId,
      lines: lines.map(({ amount: _amount, ...l }) => l),
      opportunityId: opportunityId || null,
      validUntil: validUntil || null,
      notes: notes.trim() || null,
    });
    if (ok) {
      setLines([]);
      setNotes("");
    }
    return ok;
  });

  return (
    <Dialog open={d.open} onOpenChange={d.setOpen}>
      <DialogTrigger asChild>
        <Button disabled={!card || accounts.length === 0}>
          <Plus className="mr-2 h-4 w-4" aria-hidden /> New proposal
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>New proposal</DialogTitle>
          <DialogDescription>
            {card
              ? `Every line is priced from ${card.name} v${card.version}. Anything the card does not cover is flagged for pricing approval.`
              : "No published rate card is available, so a proposal cannot be priced."}
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <div className="grid gap-3 sm:grid-cols-2">
            <AccountPicker accounts={accounts} value={accountId} onChange={setAccountId} />
            <div>
              <Label>Opportunity (optional)</Label>
              <Select value={opportunityId} onValueChange={setOpportunityId}>
                <SelectTrigger>
                  <SelectValue placeholder="Not linked" />
                </SelectTrigger>
                <SelectContent>
                  {opportunities.map((o) => (
                    <SelectItem key={o.id} value={o.id}>
                      {o.opportunity_ref} · {o.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="rounded-lg border p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Add a priced line</p>
            <div className="mt-2 grid gap-2 sm:grid-cols-4">
              <Select
                value={service}
                onValueChange={(v) => {
                  setService(v);
                  setLineId("");
                }}
              >
                <SelectTrigger className="capitalize">
                  <SelectValue placeholder="Service" />
                </SelectTrigger>
                <SelectContent>
                  {services.map((s) => (
                    <SelectItem key={s} value={s} className="capitalize">
                      {s.replace(/_/g, " ")}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Select value={lineId} onValueChange={setLineId}>
                <SelectTrigger className="sm:col-span-2">
                  <SelectValue placeholder="Scope, vehicle and basis" />
                </SelectTrigger>
                <SelectContent>
                  {options.map((o) => (
                    <SelectItem key={o.id} value={o.id}>
                      {o.scope_label} · {o.category_code} · {o.pricing_basis.replace(/_/g, " ")} ·{" "}
                      {money(o.amount, o.currency)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <div className="flex gap-2">
                <Input
                  type="number"
                  min={1}
                  value={quantity}
                  onChange={(e) => setQuantity(e.target.value)}
                  aria-label="Quantity"
                />
                <Button variant="outline" onClick={addLine} disabled={!lineId}>
                  Add
                </Button>
              </div>
            </div>
            {lines.length > 0 && (
              <div className="mt-3 space-y-1.5">
                {lines.map((l, i) => (
                  <div key={i} className="flex items-center justify-between gap-2 text-sm">
                    <span className="truncate">
                      {l.service_code.replace(/_/g, " ")} · {l.scope_label} · {l.category_code} × {l.quantity}
                    </span>
                    <span className="flex items-center gap-2">
                      <span className="tabular-nums">{money(l.amount * l.quantity, card?.currency ?? "KES")}</span>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => setLines((prev) => prev.filter((_, j) => j !== i))}
                      >
                        Remove
                      </Button>
                    </span>
                  </div>
                ))}
                <div className="flex justify-between border-t pt-2 text-sm font-semibold">
                  <span>Total</span>
                  <span className="tabular-nums">{money(total, card?.currency ?? "KES")}</span>
                </div>
              </div>
            )}
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <Label htmlFor="q-valid">Valid until</Label>
              <Input id="q-valid" type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="q-notes">Notes</Label>
              <Input id="q-notes" value={notes} onChange={(e) => setNotes(e.target.value)} />
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button onClick={() => void d.submit()} disabled={d.saving || !ready}>
            {d.saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden />} Issue proposal
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function NewContractDialog({
  accounts,
  opportunities,
  templates,
  card,
  onCreate,
}: {
  accounts: CrmAccount[];
  opportunities: BookOpportunity[];
  templates: ContractTemplate[];
  card: RateCard | null;
  onCreate: (input: {
    accountId: string;
    templateId: string;
    customerLegalName: string;
    contractTerm: string | null;
    effectiveDate: string | null;
    paymentTerms: string | null;
    selectedServices: string[];
    opportunityId: string | null;
    rateCardId: string | null;
  }) => Promise<boolean>;
}) {
  const [accountId, setAccountId] = React.useState("");
  const [templateId, setTemplateId] = React.useState("");
  const [legalName, setLegalName] = React.useState("");
  const [term, setTerm] = React.useState("");
  const [effective, setEffective] = React.useState("");
  const [paymentTerms, setPaymentTerms] = React.useState("");
  const [services, setServices] = React.useState<string[]>([]);
  const available = serviceCodesOf(card);
  const ready = !!accountId && !!templateId && legalName.trim().length > 0;

  const d = useDialog(async () => {
    if (!ready) return false;
    const ok = await onCreate({
      accountId,
      templateId,
      customerLegalName: legalName.trim(),
      contractTerm: term.trim() || null,
      effectiveDate: effective || null,
      paymentTerms: paymentTerms.trim() || null,
      selectedServices: services,
      opportunityId: null,
      rateCardId: card?.id ?? null,
    });
    if (ok) {
      setLegalName("");
      setServices([]);
    }
    return ok;
  });

  return (
    <Dialog open={d.open} onOpenChange={d.setOpen}>
      <DialogTrigger asChild>
        <Button disabled={templates.length === 0 || accounts.length === 0}>
          <Plus className="mr-2 h-4 w-4" aria-hidden /> New contract
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>Draft a contract</DialogTitle>
          <DialogDescription>
            Drafted from an approved template. {opportunities.length > 0 ? "" : "No opportunity is linked."}
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <AccountPicker accounts={accounts} value={accountId} onChange={setAccountId} />
          <div>
            <Label>Template</Label>
            <Select value={templateId} onValueChange={setTemplateId}>
              <SelectTrigger>
                <SelectValue placeholder="Choose a template" />
              </SelectTrigger>
              <SelectContent>
                {templates.map((t) => (
                  <SelectItem key={t.id} value={t.id}>
                    {t.name} v{t.version} · {t.status}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="c-legal">Customer legal name</Label>
            <Input id="c-legal" value={legalName} onChange={(e) => setLegalName(e.target.value)} />
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div>
              <Label htmlFor="c-term">Term</Label>
              <Input id="c-term" placeholder="12 months" value={term} onChange={(e) => setTerm(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="c-eff">Effective date</Label>
              <Input id="c-eff" type="date" value={effective} onChange={(e) => setEffective(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="c-pay">Payment terms</Label>
              <Input id="c-pay" placeholder="30 days" value={paymentTerms} onChange={(e) => setPaymentTerms(e.target.value)} />
            </div>
          </div>
          {available.length > 0 && (
            <div>
              <Label>Services covered</Label>
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                {available.map((s) => {
                  const on = services.includes(s);
                  return (
                    <Button
                      key={s}
                      type="button"
                      size="sm"
                      variant={on ? "default" : "outline"}
                      className="capitalize"
                      onClick={() =>
                        setServices((prev) => (on ? prev.filter((x) => x !== s) : [...prev, s]))
                      }
                    >
                      {s.replace(/_/g, " ")}
                    </Button>
                  );
                })}
              </div>
            </div>
          )}
        </div>
        <DialogFooter>
          <Button onClick={() => void d.submit()} disabled={d.saving || !ready}>
            {d.saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden />} Draft contract
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function NewServiceOrderDialog({
  contracts,
  card,
  onCreate,
}: {
  contracts: BookContract[];
  card: RateCard | null;
  onCreate: (input: {
    contractInstanceId: string;
    rateCardId: string;
    title: string;
    services: string[];
    locations: string[];
    vehicleCategories: string[];
    validity: string | null;
    commercialTerms: string | null;
  }) => Promise<boolean>;
}) {
  const [contractId, setContractId] = React.useState("");
  const [title, setTitle] = React.useState("");
  const [locations, setLocations] = React.useState("");
  const [vehicles, setVehicles] = React.useState("");
  const [validity, setValidity] = React.useState("");
  const [terms, setTerms] = React.useState("");
  const [services, setServices] = React.useState<string[]>([]);
  const available = serviceCodesOf(card);
  const contract = contracts.find((c) => c.id === contractId);
  const rateCardId = contract?.rate_card_id ?? card?.id ?? "";
  const ready = !!contractId && title.trim().length > 0 && !!rateCardId;

  const d = useDialog(async () => {
    if (!ready) return false;
    const ok = await onCreate({
      contractInstanceId: contractId,
      rateCardId,
      title: title.trim(),
      services,
      locations: locations.split(",").map((s) => s.trim()).filter(Boolean),
      vehicleCategories: vehicles.split(",").map((s) => s.trim()).filter(Boolean),
      validity: validity.trim() || null,
      commercialTerms: terms.trim() || null,
    });
    if (ok) {
      setTitle("");
      setLocations("");
      setVehicles("");
      setServices([]);
      setTerms("");
    }
    return ok;
  });

  return (
    <Dialog open={d.open} onOpenChange={d.setOpen}>
      <DialogTrigger asChild>
        <Button disabled={contracts.length === 0}>
          <Plus className="mr-2 h-4 w-4" aria-hidden /> New service order
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>New service order</DialogTitle>
          <DialogDescription>What this contract actually delivers, and where.</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <div>
            <Label>Contract</Label>
            <Select value={contractId} onValueChange={setContractId}>
              <SelectTrigger>
                <SelectValue placeholder="Choose a contract" />
              </SelectTrigger>
              <SelectContent>
                {contracts.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.customer_legal_name} · {c.status}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="so-title">Title</Label>
            <Input id="so-title" value={title} onChange={(e) => setTitle(e.target.value)} />
          </div>
          {available.length > 0 && (
            <div>
              <Label>Services</Label>
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                {available.map((s) => {
                  const on = services.includes(s);
                  return (
                    <Button
                      key={s}
                      type="button"
                      size="sm"
                      variant={on ? "default" : "outline"}
                      className="capitalize"
                      onClick={() => setServices((prev) => (on ? prev.filter((x) => x !== s) : [...prev, s]))}
                    >
                      {s.replace(/_/g, " ")}
                    </Button>
                  );
                })}
              </div>
            </div>
          )}
          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <Label htmlFor="so-loc">Locations (comma separated)</Label>
              <Input id="so-loc" value={locations} onChange={(e) => setLocations(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="so-veh">Vehicle categories (comma separated)</Label>
              <Input id="so-veh" value={vehicles} onChange={(e) => setVehicles(e.target.value)} />
            </div>
          </div>
          <div>
            <Label htmlFor="so-valid">Validity</Label>
            <Input id="so-valid" placeholder="1 Mar 2026 – 28 Feb 2027" value={validity} onChange={(e) => setValidity(e.target.value)} />
          </div>
          <div>
            <Label htmlFor="so-terms">Commercial terms</Label>
            <Textarea id="so-terms" rows={3} value={terms} onChange={(e) => setTerms(e.target.value)} />
          </div>
        </div>
        <DialogFooter>
          <Button onClick={() => void d.submit()} disabled={d.saving || !ready}>
            {d.saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden />} Create service order
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
